# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: news_powered_by_metaphor
    build: .
    command: uwsgi --http 0.0.0.0:5000 --module news_powered_by_metaphor.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/news_powered_by_metaphor.db
    volumes:
      - ./news_powered_by_metaphor:/code/news_powered_by_metaphor
      - ./db/:/db/
    ports:
      - "5000:5000"
